### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by derjust** [cloudhut/kminion#29]
While our Kafka cluster was rebalancing we saw in the kafka-minion logs
```
kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.
```
which lead to a crash of kafka-minion:
```
failed to fetch high watermarks from broker","time":"2020-02-09T13:34:04Z
--
/app/main.go:48 +0x2b7
main.main()
/app/kafka/cluster.go:74 +0x255
github.com/google-cloud-tools/kafka-minion/kafka.NewCluster(0xc0000a26c0, 0xc000094ea0, 0xc000094ea0)
/app/kafka/connection_helper.go:38 +0x151
github.com/google-cloud-tools/kafka-minion/kafka.saramaClientConfig(0xc0000a26c0, 0xc00012d980)
goroutine 1 [running]:
 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x932571]
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by weeco** [comment]
Hey @derjust ,
thank you for the crash report. Can you add the version you are using? I took a look at connection_helper.go:38 which is a comment line in v1.0.0

**Comment by josepplaltg** [comment]
Same here without cluster rebalancing, simply stopped to work 2 weeks ago.

```
{"level":"info","msg":"Starting kafka minion version2.1.1","time":"2020-05-27T08:45:11Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x9325b1]

goroutine 1 [running]:
github.com/google-cloud-tools/kafka-minion/kafka.saramaClientConfig(0xc000184240, 0xc000135980)
	/app/kafka/connection_helper.go:38 +0x151
github.com/google-cloud-tools/kafka-minion/kafka.NewCluster(0xc000184240, 0xc0001143c0, 0xc0001143c0)
	/app/kafka/cluster.go:74 +0x255
main.main()
	/app/main.go:53 +0x2c2
```

**Comment by weeco** [comment]
V2 is a rewrite and therefore this should be no a no longer valid issue.
