### ISSUE TITLE
kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

### ISSUE THREAD

**Issue by annpricksedmund** [cloudhut/kminion#32]
Hello,

 When I connect kafka (With SASL authentication - SCAM-SH-512) from kafka-minion, I am getting below error.
 **"panic","module":"cluster","msg":"failed to start client","reason":"kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"**

FYI, I have used helm chart and set all the necessary parameters required for SASL SCRAM. Kindly help me to resolve the issue.

**Comment by weeco** [comment]
Hey @annpricksedmund , can you please disable logging at the debug level and post your logs? As far as I see it's currently not possible to turn on debug logs from sarama (which is a pitty for debugging problems like yours).

But maybe you'll see something obvious after enabling debug logs.

**Comment by annpricksedmund** [comment]
Thanks for the response. PFB, the debug info.

{"level":"info","msg":"Starting kafka minion version1.0.0","time":"2020-02-16T15:27:42Z"}
{"level":"debug","msg":"Sarama client config has been created successfully","time":"2020-02-16T15:27:42Z"}
{"address":"10.0.0.10:8725,10.0.0.11:8725,10.0.0.12:8725","level":"info","module":"cluster","msg":"connecting to kafka cluster","time":"2020-02-16T15:27:42Z"}
{"address":"10.0.0.10:8725,10.0.0.11:8725,10.0.0.12:8725","level":"panic","module":"cluster","msg":"failed to start client","reason":"kafka: client has run out of available brokers to talk to (Is your cluster reachable?)","time":"2020-02-16T15:27:43Z"}
panic: (*logrus.Entry) (0x94ef00,0xc00012e150)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000072360, 0xc00012a7b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2ce
github.com/sirupsen/logrus.(*Entry).Log(0xc00012e0e0, 0x0, 0xc000127878, 0x1, 0x1)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xed
github.com/sirupsen/logrus.(*Entry).Logf(0xc00012e0e0, 0xc000000000, 0x95cf3c, 0x16, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 +0xe4
github.com/sirupsen/logrus.(*Entry).Panicf(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:352
github.com/google-cloud-tools/kafka-minion/kafka.NewCluster(0xc00011e000, 0xc000072d20, 0xc000030880)
	/app/kafka/cluster.go:80 +0x759
main.main()
	/app/main.go:48 +0x2b6

**Comment by weeco** [comment]
Do you use the image built from master? v1.0.0 has no scram support and I haven't released a new version since then.

**Comment by annpricksedmund** [comment]
No. I took helm chart and the image whatever mentioned in that

**Comment by annpricksedmund** [comment]
I built the image from master now and getting the same issue. PFB, the logs.

```
{"level":"info","msg":"Starting kafka minion version1.1.2","time":"2020-02-17T08:05:30Z"}
{"level":"debug","msg":"Sarama client config has been set for scram 512","time":"2020-02-17T08:05:30Z"}
{"level":"debug","msg":"Sarama client config has been created successfully","time":"2020-02-17T08:05:30Z"}
{"address":"10.0.0.10:8725,10.0.0.11:8725,10.0.0.12:8725","level":"info","module":"cluster","msg":"connecting to kafka cluster","time":"2020-02-17T08:05:30Z"}
{"address":"10.0.0.10:8725,10.0.0.11:8725,10.0.0.12:8725","level":"panic","module":"cluster","msg":"failed to start client","reason":"kafka: client has run out of available brokers to talk to (Is your cluster reachable?)","time":"2020-02-17T08:05:30Z"}
panic: (*logrus.Entry) (0xaaa260,0xc00036a070)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000e6a10, 0xc00033e480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2db
github.com/sirupsen/logrus.(*Entry).Log(0xc00036a000, 0x0, 0xc000157848, 0x1, 0x1)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xeb
github.com/sirupsen/logrus.(*Entry).Logf(0xc00036a000, 0xc000000000, 0xababa4, 0x16, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 +0xe2
github.com/sirupsen/logrus.(*Entry).Panicf(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:352
github.com/google-cloud-tools/kafka-minion/kafka.NewCluster(0xc0000c67e0, 0xc0000bade0, 0xc0000bade0)
	/app/kafka/cluster.go:80 +0x733
main.main()
	/app/main.go:48 +0x2b7
```

**Comment by weeco** [comment]
You don't need to build the images yourself, you can take one from here: https://quay.io/repository/google-cloud-tools/kafka-minion?tab=tags

I just pushed code which attaches a logger for sarama if you set the loglevel to debug. Please try running it again and you should see some more log messages

**Comment by annpricksedmund** [comment]
PFB, the logs.

```
{"level":"info","msg":"Starting kafka minion version1.0.0","time":"2020-02-18T07:02:42Z"}
{"level":"debug","msg":"Sarama client config has been set for scram 512","time":"2020-02-18T07:02:42Z"}
{"level":"debug","msg":"Sarama client config has been created successfully","time":"2020-02-18T07:02:42Z"}
{"address":"10.0.0.10:8725,10.0.0.11:8725,10.0.0.12:8725","level":"info","module":"cluster","msg":"connecting to kafka cluster","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"Initializing new client","source":"sarama","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker 10.0.0.10:8725\n","source":"sarama","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"Connected to broker at 10.0.0.10:8725 (unregistered)\n","source":"sarama","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"Closed connection to broker 10.0.0.10:8725\n","source":"sarama","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker 10.0.0.11:8725\n","source":"sarama","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"Connected to broker at 10.0.0.11:8725 (unregistered)\n","source":"sarama","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"Closed connection to broker 10.0.0.11:8725\n","source":"sarama","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker 10.0.0.12:8725\n","source":"sarama","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"Connected to broker at 10.0.0.12:8725 (unregistered)\n","source":"sarama","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"Closed connection to broker 10.0.0.12:8725\n","source":"sarama","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"client/metadata no available broker to send metadata request to","source":"sarama","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"client/brokers resurrecting 3 dead seed brokers","source":"sarama","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"client/metadata retrying after 250ms... (3 attempts remaining)\n","source":"sarama","time":"2020-02-18T07:02:42Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker 10.0.0.10:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Connected to broker at 10.0.0.10:8725 (unregistered)\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Closed connection to broker 10.0.0.10:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker 10.0.0.11:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Connected to broker at 10.0.0.11:8725 (unregistered)\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Closed connection to broker 10.0.0.11:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker 10.0.0.12:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Connected to broker at 10.0.0.12:8725 (unregistered)\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Closed connection to broker 10.0.0.12:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata no available broker to send metadata request to","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/brokers resurrecting 3 dead seed brokers","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata retrying after 250ms... (2 attempts remaining)\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker 10.0.0.10:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Connected to broker at 10.0.0.10:8725 (unregistered)\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Closed connection to broker 10.0.0.10:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker 10.0.0.11:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Connected to broker at 10.0.0.11:8725 (unregistered)\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Closed connection to broker 10.0.0.11:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker 10.0.0.12:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Connected to broker at 10.0.0.12:8725 (unregistered)\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Closed connection to broker 10.0.0.12:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata no available broker to send metadata request to","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/brokers resurrecting 3 dead seed brokers","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata retrying after 250ms... (1 attempts remaining)\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker 10.0.0.10:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Connected to broker at 10.0.0.10:8725 (unregistered)\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Closed connection to broker 10.0.0.10:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker 10.0.0.11:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Connected to broker at 10.0.0.11:8725 (unregistered)\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Closed connection to broker 10.0.0.11:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker 10.0.0.12:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Connected to broker at 10.0.0.12:8725 (unregistered)\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Closed connection to broker 10.0.0.12:8725\n","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/metadata no available broker to send metadata request to","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"client/brokers resurrecting 3 dead seed brokers","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"level":"info","msg":"Closing Client","source":"sarama","time":"2020-02-18T07:02:43Z"}
{"address":"10.0.0.10:8725,10.0.0.11:8725,10.0.0.12:8725","level":"panic","module":"cluster","msg":"failed to start client","reason":"kafka: client has run out of available brokers to talk to (Is your cluster reachable?)","time":"2020-02-18T07:02:43Z"}
panic: (*logrus.Entry) (0xaaa260,0xc0001f2e70)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000114a10, 0xc0002b7200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2db
github.com/sirupsen/logrus.(*Entry).Log(0xc0001f2e00, 0x0, 0xc00014f848, 0x1, 0x1)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xeb
github.com/sirupsen/logrus.(*Entry).Logf(0xc0001f2e00, 0xc000000000, 0xababaa, 0x16, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 +0xe2
github.com/sirupsen/logrus.(*Entry).Panicf(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:352
github.com/google-cloud-tools/kafka-minion/kafka.NewCluster(0xc0000ce7e0, 0xc000100de0, 0xc000100de0)
	/app/kafka/cluster.go:80 +0x733
main.main()
	/app/main.go:53 +0x2c2
```

**Comment by weeco** [comment]
These are all the debug logs you could get straight from Sarama (our kafka client lib). Unfortunately I can not test the SCRAM integration myself, but maybe jchomat can help. He submitted the PR: https://github.com/cloudworkz/kafka-minion/pull/26 .

The PR is pretty much the same as suggested in Sarama's examples.

**Comment by weeco** [comment]
Please try again with v2 which uses a completely different Kafka client. SCRAM-SHA authentication has been successfully tested there.
